package com.cloudcomputing.fall2018.courseservice.datamodel;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName="announcement")
public class Announcement {
    String ID;
    String announcementId;
    String announcementText;
    String boardId;
    
    
    public Announcement(){

    }

	public Announcement(String announcementId, String announcementText, String boardId) {
		super();
		this.announcementId = announcementId;
		this.announcementText = announcementText;
		this.boardId = boardId;
	}

	@DynamoDBHashKey(attributeName="ID")
	@DynamoDBAutoGeneratedKey
	public String getID() {
		return ID;
	}


	public void setID(String iD) {
		ID = iD;
	}

	@DynamoDBIndexRangeKey(attributeName="announcementId", globalSecondaryIndexName = "announcementId-index")
	public String getAnnouncementId() {
		return announcementId;
	}

	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName="announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}
	
	@DynamoDBIndexHashKey(attributeName="boardId", globalSecondaryIndexName = "boardId-index")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

}
