package com.cloudcomputing.fall2018.courseservice.datamodel;

import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName="professor")
public class Professor {
	private String ID;
	private String firstName;
	private String department;
	private long professorId;
	private String joiningDate;
	
	public Professor() {
		
	}
	
	public Professor(long professorId, String firstName, String department, String joiningDate) {
		this.professorId = professorId;
		this.firstName = firstName;
		this.department = department;
		this.joiningDate = joiningDate;
	}

	@DynamoDBHashKey(attributeName="ID")
	@DynamoDBAutoGeneratedKey
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}

	@DynamoDBAttribute(attributeName="firstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBIndexHashKey(attributeName="professorId", globalSecondaryIndexName = "professorId-index")
	public long getProfessorId() {
		return professorId;
	}

	public void setProfessorId(long professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName="joiningDate")
	public String getJoiningDate() {
		return joiningDate;
	}

	public void setJoiningDate(String joingDate) {
		this.joiningDate = joingDate;
	}

	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "ProfId=" + getProfessorId() + ", firstName=" + getFirstName()
				+ ", department=" + getDepartment() + ", joiningDate=" + getJoiningDate();
	}
}




	
	


