package com.cloudcomputing.fall2018.courseservice.datamodel;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@XmlRootElement
@DynamoDBTable(tableName ="registrar")
public class Registrar {
    private String ID;
    private String registrationId;
    private String offeringId;
    private String offeringType;
    private String department;
    private int perUnitPrice;

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getID() {
        return ID;
    }

    public void setID(String id) {
        ID = id;
    }

    @DynamoDBIndexHashKey(attributeName = "registrarId", globalSecondaryIndexName = "registrarId-index")
    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    @DynamoDBAttribute(attributeName = "offeringId")
    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }

    @DynamoDBAttribute(attributeName = "offeringType")
    public String getOfferingType() {
        return offeringType;
    }

    public void setOfferingType(String offeringType) {
        this.offeringType = offeringType;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "perUnitPrice")
    public int getPerUnitPrice() {
        return perUnitPrice;
    }

    public void setPerUnitPrice(int perUnitPrice) {
        this.perUnitPrice = perUnitPrice;
    }

}


